export class ParsePhrasalVerbs {
    private static phrasalVerbsString = this.createPhrasalVerbsString();
    private static createPhrasalVerbsString() {
        const phrasalVerbs = [
            'Act on',
            'Act out',
            'Act up',
            'Act up to',
            'Act upon',
            'Answer back',
            'Answer for',
            'Answer to',
            'Ask after',
            'Ask around (round)',
            'Ask for',
            'Ask in',
            'Ask out',
            'Ask round',
            'Ask over',
            'Back down',
            'Back into',
            'Back off',
            'Back onto',
            'Back out',
            'Back up',
            'Be above',
            'Be along',
            'Be around',
            'Be cut out for',
            'Be down',
            'Be down to',
            'Be down on',
            'Be down with',
            'Be fed up',
            'Be in for',
            'Be in on',
            'Be on about',
            'Be on to',
            'Be out for',
            'Be there for',
            'Be snowed under',
            'Be taken aback',
            'Be taken with',
            'Be up for',
            'Be up to',
            'Be with',
            'Beat down',
            'Beat off',
            'Beat out',
            'Beat up',
            'Blow away',
            'Blow down',
            'Blow off',
            'Blow out',
            'Blow over',
            'Blow past',
            'Blow up',
            'Break away',
            'Break down',
            'Break even',
            'Break in',
            'Break off',
            'Break into',
            'Break out',
            'Break through',
            'Break up',
            'Bring about',
            'Bring along',
            'Bring around',
            'Bring back',
            'Bring down',
            'Bring forth',
            'Bring forward',
            'Bring in',
            'Bring off',
            'Bring out',
            'Bring round',
            'Bring to',
            'Bring up',
            'Call away',
            'Call down',
            'Call for',
            'Call in',
            'Call off',
            'Call on',
            'Call out',
            'Carry off',
            'Carry on',
            'Carry out',
            'Carry over',
            'Check out',
            'Check up',
            'Check up on',
            'Come about',
            'Come across',
            'Come after',
            'Come along',
            'Come apart',
            'Come around',
            'Come at',
            'Come away',
            'Come back',
            'Come before',
            'Come between',
            'Come by',
            'Come down',
            'Come down on',
            'Come down upon',
            'Come down to',
            'Come down with',
            'Come for',
            'Come forth',
            'Come from',
            'Come in',
            'Come in for',
            'Come into',
            'Come off',
            'Come on',
            'Come out in',
            'Come out of',
            'Come out with',
            'Come over',
            'Come round',
            'Come through',
            'Come through with',
            'Come to',
            'Come together',
            'Come under',
            'Come up',
            'Come up to',
            'Come up with',
            'Come upon',
            'Come with',
            'Crack down',
            'Crack down on',
            'Crack on',
            'Crack up',
            'Crack out',
            'Cut back',
            'Cut down',
            'Cut off',
            'Cut out',
            'Cut through',
            'Cut up',
            'Fall about',
            'Fall apart',
            'Fall away',
            'Fall behind',
            'Fall down',
            'Fall for',
            'Fall in',
            'Fall in with',
            'Fall into',
            'Fall off',
            'Fall on',
            'Fall out',
            'Fall through',
            'Fall under',
            'Fall upon',
            'Fill in',
            'Fill out',
            'Fill up',
            'Get about',
            'Get across',
            'Get after',
            'Get ahead',
            'Get ahead of',
            'Get along',
            'Get along with',
            'Get around',
            'Get around to',
            'Get at',
            'Get away',
            'Get away from',
            'Get away with',
            'Get back',
            'Get back at',
            'Get back to',
            'Get behind',
            'Get behind with',
            'Get by',
            'Get down',
            'Get down on',
            'Get down to',
            'Get in',
            'Get in with',
            'Get into',
            'Get it',
            'Get it on',
            'Get it together',
            'Get it over with',
            'Get it up',
            'Get off',
            'Get off on',
            'Get on',
            'Get on to',
            'Get on for',
            'Get on with',
            'Get onto',
            'Get out',
            'Get out of',
            'Get over',
            'Get over with',
            'Get rid of',
            'Get stuck in',
            'Get stuck into',
            'Get taken in',
            'Get through',
            'Get through to',
            'Get to',
            'Get together',
            'Get up',
            'Get up to',
            'Get used',
            'Get with',
            'Give away',
            'Give back',
            'Give forth',
            'Give in',
            'Give in to',
            'Give it up for/to',
            'Give of oneself',
            'Give off',
            'Give out',
            'Give over',
            'Give up',
            'Give up on',
            'Give way',
            'Give way to',
            'Give yourself up',
            'Go about',
            'Go across',
            'Go after',
            'Go against',
            'Go ahead',
            'Go ahead with',
            'Go all out',
            'Go along',
            'Go around',
            'Go at',
            'Go away',
            'Go back',
            'Go before',
            'Go below',
            'Go by',
            'Go down',
            'Go down with',
            'Go for',
            'Go for it',
            'Go forward',
            'Go in',
            'Go in for',
            'Go in with',
            'Go into',
            'Go off',
            'Go off with',
            'Go on',
            'Go on to',
            'Go on about',
            'Go on at',
            'Go on with',
            'Go out',
            'Go out for',
            'Go out to',
            'Go over',
            'Go over to',
            'Go so far as',
            'Go past',
            'Go round',
            'Go through',
            'Go through with',
            'Go to',
            'Go together',
            'Go towards',
            'Go under',
            'Go up',
            'Go up for',
            'Go with',
            'Go without',
            'Hang about',
            'Hang on',
            'Hang out',
            'Hang over',
            'Hang together',
            'Hang up',
            'Hold back',
            'Hold down',
            'Hold in',
            'Hold off',
            'Hold on',
            'Hold out',
            'Hold over',
            'Hold up',
            'Jump around',
            'Jump at',
            'Jump down',
            'Jump in',
            'Jump off',
            'Jump on',
            'Jump out',
            'Jump up',
            'Keep across',
            'Keep around',
            'Keep at',
            'Keep away',
            'Keep away from',
            'Keep back',
            'Keep down',
            'Keep from',
            'Keep in',
            'Keep off',
            'Keep on',
            'Keep out',
            'Keep out of',
            'Keep to oneself',
            'Keep up',
            'Keep up with',
            'Kick around',
            'Kick back',
            'Kick down',
            'Kick in',
            'Kick off',
            'Kick out',
            'Kick ou',
            'Kick up',
            'Knock about',
            'Knock back',
            'Knock down',
            'Knock it off',
            'Knock off',
            'Knock out',
            'Knock ou',
            'Knock over',
            'Knock together',
            'Knock up',
            'Lay by',
            'Lay down',
            'Lay low',
            'Lay off',
            'Lay on',
            'Lay out',
            'Lay up',
            'Live down',
            'Live off',
            'Live on',
            'Live out',
            'Live through',
            'Live up',
            'Let down',
            'Let in',
            'Let in on',
            'Let off',
            'Let on',
            'Let out',
            'Let past',
            'Let up',
            'Look after',
            'Look ahead',
            'Look back',
            'Look down on',
            'Look around',
            'Look at',
            'Look for',
            'Look forward to',
            'Look in (on sby)',
            'Look into',
            'Look on',
            'Look on as',
            'Look out',
            'Look out for',
            'Look round',
            'Look through',
            'Look to',
            'Look up',
            'Look up to',
            'Look upon',
            'Look upon as',
            'Make after',
            'Make away with',
            'Make for',
            'Make into',
            'Make it up to',
            'Make of',
            'Make off',
            'Make off with',
            'Make out',
            'Make out of',
            'Make over',
            'Make towards',
            'Make up',
            'Make up for',
            'Make up to',
            'Make way',
            'Mess about',
            'Mess around',
            'Mess up',
            'Mess with',
            'Move forward',
            'Move on',
            'Move out',
            'Move up',
            'Pass away',
            'Pass by',
            'Pass down',
            'Pass off',
            'Pass on',
            'Pass out',
            'Pass over',
            'Pass round',
            'Pass through',
            'Pass to',
            'Pass up',
            'Pick apart',
            'Pick at',
            'Pick off',
            'Pick on',
            'Pick out',
            'Pick through',
            'Pick up',
            'Pick up after',
            'Pick up on',
            'Pick up on:',
            'Pick yourself up',
            'Play along',
            'Play around',
            'Play at',
            'Play down',
            'Play off',
            'Play out',
            'Play up',
            'Pull ahead',
            'Pull apart',
            'Pull away',
            'Pull in',
            'Pull off',
            'Pull on',
            'Pull out',
            'Pull over',
            'Pull up',
            'Put (effort) into',
            'Put across',
            'Put aside',
            'Put asunder',
            'Put away',
            'Put back',
            'Put by',
            'Put down',
            'Put down as',
            'Put down for',
            'Put down to',
            'Put forward',
            'Put in',
            'Put in practice',
            'Put off',
            'Put of',
            'Put on',
            'Put on:',
            'Put oneself across',
            'Put out',
            'Put ove',
            'Put past',
            'Put through',
            'Put throug',
            'Put to',
            'Put together',
            'Put towards',
            'Put up',
            'Put up with',
            'Run about',
            'Run across',
            'Run after',
            'Run against',
            'Run along',
            'Run around',
            'Run around after',
            'Run away',
            'Run away with',
            'Run back',
            'Run by',
            'Run down',
            'Run for it',
            'Run in',
            'Run into',
            'Run low',
            'Run off',
            'Run off with',
            'Run on',
            'Run out',
            'Run ou',
            'Run out on',
            'Run over',
            'Run past',
            'Run through',
            'Run to',
            'Run up',
            'Run up against',
            'Run up on',
            'Run with',
            'See in',
            'See into',
            'See out',
            'See through',
            'See to',
            'Send away',
            'Send away for',
            'Send back',
            'Send down',
            'Send off:',
            'Send out for',
            'Send up',
            'Set about',
            'Set aside',
            'Set back',
            'Set down',
            'Set forth',
            'Set in',
            'Set off',
            'Set on',
            'Set out',
            'Set up',
            'Set upon',
            'Speak for',
            'Speak for oneself',
            'Speak of',
            'Speak out',
            'Speak to',
            'Speak up',
            'Stand aside',
            'Stand back',
            'Stand by',
            'Stand for',
            'Stand in for',
            'Stand off',
            'Stand out',
            'Stand',
            'out',
            'Stand up',
            'Stand up for',
            'Stand up to',
            'Take aback',
            'Take after',
            'Take against',
            'Take apart',
            'Take aside',
            'Take away',
            'Take away from',
            'Take back',
            'Take down',
            'Take for',
            'Take in',
            'Take it away',
            'Take it out in',
            'Take it out on',
            'Take it upon oneself',
            'Take off',
            'Take on',
            'Take out',
            'Take over',
            'Take pity',
            'Take through',
            'Take to',
            'Take up',
            'Take up with',
            'Take upon oneself',
            'Throw away',
            'Throw down',
            'Throw in',
            'Throw off',
            'Throw on',
            'Throw out',
            'Throw up',
            'Turn against',
            'Turn around',
            'Turn back',
            'Turn down',
            'Turn in',
            'Turn into',
            'Turn off',
            'Turn on',
            'Turn out',
            'Turn over',
            'Turn over:',
            'Turn round',
            'Turn to',
            'Turn up',
            'Turn upside down',
            'Walk away',
            'Walk away from',
            'Walk in on',
            'Walk into',
            'Walk it off',
            'Walk out',
            'Wash away',
            'Wash down',
            'Wash off',
            'Wash out',
            'Wash over',
            'Wash up',
            'Work on',
            'Work out',
            'Work over',
            'Work sb out',
            'Work smt off',
            'Work sth out',
            'Work through',
            'Work up',
            'Try back',
            'Try for',
            'Try it on',
            'Try on',
            'Try out',
            'Think about/of',
            'Think ahead',
            'Think over',
            'Think through',
            'Think up',
            'Spring back',
            'Spring on',
            'Spring from/ Spring up',
            'Spring for',
            'Account for',
            'Account to',
            'Admire to',
            'Adopt out',
            'Age out',
            'Aim at',
            'Aim at/to',
            'Allow for',
            'Attend to',
            'Bail out',
            'Ball out',
            'Ball up',
            'Balls up',
            'Bear on',
            'Bear out',
            'Bear upon',
            'Bear with',
            'Believe in',
            'Block off',
            'Block out',
            'Boil down',
            'Boil off',
            'Boil over',
            'Boil up',
            'Book in',
            'Bottom out',
            'Branch out',
            'Brighten up',
            'Bubble over',
            'Buck up',
            'Buckle down',
            'Buckle up',
            'Build up',
            'Bump into',
            'Burn down',
            'Burn out',
            'Burn up',
            'Calm down',
            'Cancel out',
            'Catch on',
            'Catch up',
            'Cheer up',
            'Chew out',
            'Chew up',
            'Chicken out',
            'Chill out',
            'Clean out',
            'Clean up',
            'Clear away',
            'Clear out',
            'Close down',
            'Close in on',
            'Close off',
            'Close up',
            'Clock in',
            'Clock off',
            'Clock out',
            'Clock ou',
            'Consist in',
            'Consist of',
            'Cool down',
            'Count down',
            'Count in',
            'Count off',
            'Count on',
            'Count out',
            'Count up',
            'Crop out',
            'Cross off',
            'Cross out',
            'Cross over',
            'Cry off',
            'Cry out for',
            'Deal with',
            'Do for',
            'Do in',
            'Do up',
            'Do without',
            'Draw in',
            'Draw on',
            'Draw out',
            'Draw up',
            'Drink in',
            'Drink to',
            'Drink up',
            'Drive at',
            'Drive away',
            'Dry out',
            'Dry up',
            'Eat away',
            'Eat into',
            'Eat out',
            'Eat up',
            'Find out',
            'Finish off',
            'Finish up',
            'Finish with',
            'Fit in',
            'Fit into',
            'Fit up',
            'Fix up',
            'Force out',
            'Gear up',
            'Grow up',
            'Hand in',
            'Hand off',
            'Hand over',
            'Hand round',
            'Hash out',
            'Head off',
            'Knuckle down',
            'Lead in',
            'Lead off',
            'Lean on',
            'Leave behind',
            'Leave off',
            'Leave out',
            'Lie around',
            'Lie before',
            'Lie down',
            'Lie in',
            'Lie low',
            'Lift up',
            'Light up',
            'Lighten up',
            'Liven up',
            'Lock in',
            'Lock out',
            'Log in',
            'Log on',
            'Log out',
            'Luck out',
            'Meet up',
            'Miss out',
            'Mix up',
            'Monkey around',
            'Narrow down',
            'Open up',
            'Pack away',
            'Pack off',
            'Pack out',
            'Pack up',
            'Pay back',
            'Pay for',
            'Pay off',
            'Phase in',
            'Phase out',
            'Plan on',
            'Plough back',
            'Plough through',
            'Point out',
            'Pour out',
            'Press out',
            'Quiet down',
            'Read in',
            'Read off',
            'Read out',
            'Rely on',
            'Roll around',
            'Roll in',
            'Roll out',
            'Roll over',
            'Roll up',
            'Round out',
            'Rule in',
            'Rule out',
            'Rush off',
            'Scale back',
            'Scare off',
            'Scarf down',
            'Sell down',
            'Sell out',
            'Settle down',
            'Settle for',
            'Settle in',
            'Settle on',
            'Shake off',
            'Shake up',
            'Shade up',
            'Show in',
            'Show off',
            'Show up',
            'Shower with',
            'Shut down',
            'Shut in',
            'Shut out',
            'Shut up',
            'Sign off',
            'Sign out',
            'Sign up',
            'Sing along',
            'Sink in',
            'Sit back',
            'Sit down',
            'Sit on',
            'Sit out',
            'Sit through',
            'Sit up',
            'Skip out',
            'Sleep in',
            'Sleep on',
            'Sleep with',
            'Slide off',
            'Slow down',
            'Smoke out',
            'Smooth down',
            'Sort out',
            'Sound off',
            'Speed up',
            'Spell out',
            'Split up',
            'Spread out',
            'Sump up',
            'Start afresh',
            'Start off',
            'Start up',
            'Stay in',
            'Stay on',
            'Stay up',
            'Step back',
            'Step on it',
            'Step up',
            'Stick around',
            'Stick at',
            'Stick down',
            'Stick it out',
            'Stick out',
            'Stick to',
            'Stick up',
            'Stick up for',
            'Stick with',
            'Talk down',
            'Talk into',
            'Talk out of',
            'Talk over',
            'Talk through',
            'Think back',
            'Tip off',
            'Used to',
            'Wait for',
            'Wait up',
            'Wait upon',
            'Wake up',
            'Warm up',
            'Watch out',
            'Watch over',
            'Wipe away',
            'Wipe down',
            'Wipe up',
            'Write in',
            'Write off',
            'Write out',
            'Yield up',
            'Be named after',
            'Bring sb up',
            'Fall out with sb',
            'Get along/on with',
            'Grow apart',
            'Tell off',
            'Put up wi',
            'See off',
            'Check in',
            'Drop off',
            'Speed up:',
            'Hurry up',
            'Look forward',
            'Stop over',
            'Touch down',
            'Call back',
            'Call up',
            'Pass on (a message)',
            'Phone in',
            'Bake off',
            'Boil away',
            'Bolt down',
            'Chop up',
            'Fry up:',
            'Pig out',
            'Slice off',
            'Whip up',
            'Cook away',
            'Peel off',
            'Thaw out',
            'Mix in',
            'Bring dow',
            'Queue up/line up',
            'Ring up',
            'Shop around',
            'Pop into',
            'Wear in',
            'Set (someone) back',
            'Go with smt',
            'Splash out',
            'Note down',
            'Step down',
            'Weigh up (UK)',
            'Get on (UK)',
            'Drop in',
            'Join in',
            'Put back (UK)',
            'Run out of',
            'Level off',
            'Dress up',
            'Dress down',
            'Have on',
            'Slip on',
            'Wrap up',
            'Zip up',
            'Duck out',
            'Fish for',
            'Fish out',
            'Horse around',
            'Wolf down',
            'Beaver away',
            'Ferret out',
            'Worm out of',
            'Rat on',
            'Rabbit on (UK)',
            'Monkey with',
            'Turn turtle',
            'Squirrel away',
            'Drone on',
            'Clam up',
            'Ferret around',
            'Lark about/around (UK)',
            'Leech off',
            'Take out of the trash:',
            'Clean up/ tidy up',
            'Mop up',
            'Build on',
            'Stock up',
            'Put on (music)',
            'Drive by',
            'Be into',
            'Read up on',
            'Hand in/turn in',
            'Hand out',
            'Copy out',
            'Drop out',
            'Fill in for',
            'Slack off',
            'Fight off',
            'Pass ou',
            'Block up',
            'Lay (laid) up',
            'Swell up',
            'Clog up',
            'Dose up (UK)',
            'Start over',
            'Figure out',
            'Fork out',
            'Rip off',
            'Save up',
            'Sleep over',
            'Sleep through',
            'Sleep on it',
            'Doze off',
            'Talk ove',
            'Wrestle with',
            'Think through',
            'Run into problems',
            'Break out of',
            'Stake out',
            'Lock up',
            'Wipe out',
            'Used up',
            'Die out',
        ];
        return phrasalVerbs.join('|');
    }
}
